name: feature branch - deploy

on:
  push:
    branches: [ feature/* ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build

      - name: lookup feature name
        id: prepare_feature_name
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: |
          FEATURE_NAME="${GITHUB_REF##refs/heads/feature/}"
          echo "::set-output name=feature_name::${FEATURE_NAME}"
          echo "FEATURE-NAME: ${FEATURE_NAME}"

      - name: update gh-pages
        run: |
          FEATURE_NAME=${{steps.prepare_feature_name.outputs.feature_name}}
          TARGET_DIR=./gh-pages/dev/${FEATURE_NAME}
          git fetch
          git worktree add gh-pages gh-pages
          mkdir ./gh-pages/dev || true
          rm -r ${TARGET_DIR} || true
          mv ./build ${TARGET_DIR}
          cd ./gh-pages
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "Deployed feature ${{steps.prepare_feature_name.outputs.feature_name}}"
          git push


