name: release - deploy

on:
  push:
    tags: [ v*.* ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: lookup version
        id: prepare_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=tag_name::${TAG_NAME}"

      - name: setup nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build

      - name: update gh-pages
        run: |
          VERSION_NAME=${{steps.prepare_tag.outputs.tag_name}}
          git fetch
          git worktree add gh-pages gh-pages
          ls gh-pages | grep -v "dev" | xargs -I {} rm -r gh-pages/{}
          mv ./build/* ./gh-pages
          cd ./gh-pages
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "Deployed Release ${VERSION_NAME}"
          git tag "deployment-${VERSION_NAME}"
          git push origin gh-pages --tags
